### ISSUE TITLE
Regarding gradient

### ISSUE THREAD

**Issue by harold-guido** [r-n-w/etch_a_sketch#1]
Hey Ryan, I saw your project in TOP’s and I was shocked to see how much more efficient and clean your solution to making a gradient is. If possible could you share how it works, or whether one learns to do it later in the TOP’s curriculum. Thank you!

**Comment by ryannathanwilson** [comment]
Hi Harold, thanks I'm glad you liked it :)
I picked up tips from other people's solutions after I floundered a bit myself.
let grey = block.style.filter.match(/\d+/); is a way to use "regular expressions" to read what the current css property is. Def stole that from someone else.
The other thing for me was using grid template columns and rows to form the grid. I had tried other ways but using the grid, the mouseover effect was much smoother. Not sure why.
Most of my structured learning is from TOP, but filling in some blanks just googling things when I run into things I can't figure out. I figure that's how professionals do it anyway. Then I check other people's solutions after I've given it my best effort and make tweaks to make it better.
Happy coding!

**Comment by harold-guido** [comment]
Hey, thanks a lot for the reply. I heard about regular expressions before but had no idea it could be so useful, I will try incorporate it into my solution after googling around too. I personally had to do a lot of inventing with if statements and the sort to get a reliable value for the rgb value of a pixel, so learning this properly is going to save me a lot of lines haha. 

Thanks again for your reply learning is a lot easier when you can look and interact with others’ solutions like this.

Hope you’re well and happy coding to you too!
